:stylesheet: ../css/rubygems.css
:stylesheet: ../css/asciidoctor.css
:stylesheet: ../css/asciidoctor.min.css

link:index.html[home]

== Lucur(1)

== BRIEF DESCRIPTION

*lucur* - liblucurious command line tool

== SYNOPSIS
*lucur* [options]

*lucur* &mdash;pde VK_QUEUE_GRAPHICS_BIT

== DESCRIPTION

The *lucur* command line tool is used to assist in the construction of single application vulkan kms compositors

== OPTIONS

=== -l, &mdash;pgvl

Prints a list of all global layers on a given system that can be activated and inserted into a vulkan commands call chain. With the key layer being the
validation layer. All useful validation layers are bundled up into a layer called *VK_LAYER_KHRONOS_validation*. Vulkan validation layers are useful to enable when debugging
code as it gives you a detailed output on what you did wrong. The ouput is mostly Vulkan Structure members whose data input were wrong *(validity errors)*. There are also *runtime errors*.
When these layers are enabled, it places itself within the repective vulkan command call chain and will detail any errors caused by wrongful practices. For an in depth debugging tutorial go to
link:https://www.lunarg.com/wp-content/uploads/2018/05/Vulkan-Debug-Utils_05_18_v1.pdf[Vulkan Debug Utilities]

=== -i, &mdash;pie

Prints a list of all instance level vulkan extensions for a given system that can be activated. Basically instance extensions
allow developers to describe what an application is setup to do. It also enables the ability to utilize activated extension related vulkan function calls.

=== -d, &mdash;pde <link:https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceType.html[VkPhysicalDeviceType]>

Prints a list of all physical device level vulkan extensions for a given system that can be activated. Basically device extensions
allow developers to describe what a particular device does. It also enables the ability to utilize activated extension related vulkan function calls.

=== &nbsp;&nbsp;&nbsp;&nbsp;&mdash;pdp <link:https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceType.html[VkPhysicalDeviceType]>

Print display devices list

=== &nbsp;&nbsp;&nbsp;&nbsp;&mdash;display-info `<drm device>`

This will display any compatible (DRM Device/KMS Node) and it's capabilities. Mainly used to limit allocations and instruction
execution when calling link:dlu_drm_kms_node_enum_ouput_dev.html[dlu_drm_kms_node_enum_ouput_dev(3)]. If no
preferred DRM device available cycle through all devices and display Plane -> CTRC -> Encoder -> Connector pairs. The argument for this flag is optional

=== -v, &mdash;version

Prints the current version of lucurious API

=== -h, &mdash;help

Show help message.

== BUGS
When using the *&mdash;display-info* flag one must add include *=* if they want to specify the device they wish to query information from.
I decided on making the option to choose which kms node you want to query information for optional.

== AUTHOR
Vincent Davis Jr.
