:stylesheet: rubygems.css
:stylesheet: asciidoctor.css
:stylesheet: asciidoctor.min.css

link:index.html[home]

== dlu_set_debug_message(3)

== BRIEF DESCRIPTION

*dlu_set_debug_message* - allows API to set the output of validation layer messages by exposing a VkDebugUtilsMessengerEXT handle. 

== C SPECIFICATION

[source,c]
----
#define LUCUR_VKCOMP_API
#include <dluc/lucurious.h>

VkResult dlu_set_debug_message(
  vkcomp *app,
  int flags,
  VkDebugUtilsMessageSeverityFlagsEXT messageSeverity,
  VkDebugUtilsMessageTypeFlagsEXT messageType
);
----

== PARAMETERS

* *app*: A pointer to the link:vkcomp.html[vkcomp(3)] structure.
* *flags*: Must be 0.
* *messageSeverity*: Basically specify what a given callback function ouputs in its message. See link:https://khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDebugUtilsMessageSeverityFlagBitsEXT.html[VkDebugUtilsMessageSeverityFlagsEXT]
for enum constants.
* *messageType*: Basically specify which types of messages a callback is notified about. See link:https://khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDebugUtilsMessageTypeFlagBitsEXT.html[VkDebugUtilsMessageTypeFlagBitsEXT]
for enum constants.

== DESCRIPTION

When using this function, first query for available layers and instance extensions with link:lucur.html[lucur(1)] command line helper tool. After enable available validation layers
and instance extensions with link:dlu_create_instance.html[dlu_create_instance(3)]. The **dlu_set_debug_message(3)** function basically just changes the output of validation
layer error messages. Like to make a note that not all validation layer messages are a result of fatal errors.

== RETURN VALUES

Upon success or failure function returns one of Vulkans link:https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkResult.html[VkResult]
enum constants. These result codes are used to indicate return status information and runtime errors.

== BUGS

N/A.

== SEE ALSO

link:vkcomp.html[vkcomp(3)]
link:lucur.html[lucur(1)]

== AUTHOR

Vincent Davis Jr.